html2pdf: update to the newer Chrome web driver API
The HTML2PDF started failing with this message:

```
  File "/home/runner/work/strictdoc/strictdoc/strictdoc/export/html2pdf/html2pdf.py", line 155, in get_pdf_from_html
    result = send_devtools(driver, "Page.printToPDF", calculated_print_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/strictdoc/strictdoc/strictdoc/export/html2pdf/html2pdf.py", line 117, in send_devtools
    url = driver.command_executor._url + resource
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChromiumRemoteConnection' object has no attribute '_url'
```